### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by sugarjohnny** [Auties00/WhatsappWebRequestAnalyzer#1]
how to use and compile

**Comment by Auties00** [comment]
Download the latest version of intellij idea and from there running it will be super easy. I'll create a self contained version tomorrow so that anyone can run it easily

**Comment by Auties00** [comment]
> how to use and compile

It's ready!
https://github.com/Auties00/whatsappweb4j-request-analyzer/releases/tag/1.0
