### ISSUE TITLE
content怎么变为明文呢？

### ISSUE THREAD

**Issue by zhengshengjie666** [Auties00/WhatsappWebRequestAnalyzer#13]
Node[description=patch, content=[10, 2, 8, 9, 18, -105, 1, 8, 1, 18, -110, 1, 10, 34, 10, 32, -73, 21, -19, 112, 77, -93, -83, -8, 36, 82, -47, 88, 71, -16, -60, -82, 78, 95, -64, 65, 35, -9, -114, 99, 67, 101, -124, -2, 38, 89, -121, -13, 18, 98, 10, 96, -68, -75, 105, 95, -104, 55, -76, -28, 63, -17, -126, 111, 23, -112, -34, 18, 55, 25, -43, 84, 121, 45, 49, -56, 36, -121, -125, -33, -44, -57, 126, -35, -34, 124, -49, -121, -119, 113, -126, -42, 36, -93, -49, -105, -95, 73, 62, 1, -63, 8, 25, -83, 125, -35, 74, 42, -42, 11, -49, -34, 33, 17, 66, -77, -56, -26, 13, 11, -83, -29, 19, -42, 80, -37, -41, -15, -5, -56, -9, -77, -76, 14, -36,

**Comment by Auties00** [comment]
> Node[description=patch, content=[10, 2, 8, 9, 18, -105, 1, 8, 1, 18, -110, 1, 10, 34, 10, 32, -73, 21, -19, 112, 77, -93, -83, -8, 36, 82, -47, 88, 71, -16, -60, -82, 78, 95, -64, 65, 35, -9, -114, 99, 67, 101, -124, -2, 38, 89, -121, -13, 18, 98, 10, 96, -68, -75, 105, 95, -104, 55, -76, -28, 63, -17, -126, 111, 23, -112, -34, 18, 55, 25, -43, 84, 121, 45, 49, -56, 36, -121, -125, -33, -44, -57, 126, -35, -34, 124, -49, -121, -119, 113, -126, -42, 36, -93, -49, -105, -95, 73, 62, 1, -63, 8, 25, -83, 125, -35, 74, 42, -42, 11, -49, -34, 33, 17, 66, -77, -56, -26, 13, 11, -83, -29, 19, -42, 80, -37, -41, -15, -5, -56, -9, -77, -76, 14, -36,

You can't, it's an encoded patch. You can check out how they are generated by looking at Whatsappweb4j
