### ISSUE TITLE
Is it possible to print data in XMLNS format?

### ISSUE THREAD

**Issue by FreedomLabsIO** [Auties00/WhatsappWebRequestAnalyzer#16]
@Auties00 , is it possible to print the analyzer data in XLMNS format instead of this decoded structure?

For example, this "pair-device" message

Instead of printing 

`Received Binary Message Node[description=iq, attributes={xmlns=md, from=s.whatsapp.net, id=1155676853, type=set}, content=[Node[description=pair-device, content=[Node[description=ref, content=[50, 64, 86, 53, 75, 109, 106, 76, 119, 85, 87, 87, 81, 97, 112, 67, 105, 72, 78, 106, 55, 89, 66, 119, 83, 53, 72, 50, 100, 80, 100, 122, 101, 116, 67, 121, 85, 112, 101, 111, 49, 104, 106, 72, 104, 65, 122, 102, 53, 97, 68, 51, 85, 112, 120, 80, 99, 57, 53, 57, 48, 104, 71, 75, 65, 76, 66, 77, 119, 57, 55, 120, 85, 67, 103, 84, 81, 105, 74, 119, 61, 61]], Node[description=ref, content=[50, 64, 71, 87, 114, 75, 66, 49, 113, 48, 67, 112, 99, 111, 115, 72, 43, 52, 75, 111, 65, 86, 111, 69, 66, 98, 84, 74, 98, 48, 122, 70, 114, 74, 68, 120, 103, 54, 112, 75, 70, 67, 85, 69, 73, 55, 80, 83, 71, 65, 88, 83, 51, 120, 50, 121, 73, 97, 71, 69, 47, 105, 76, 73, 73, 51, 90, 103, 110, 89, 115, 115, 73, 104, 87, 75, 75, 107, 52, 103, 61, 61]], Node[description=ref, content=[50, 64, 82, 99, 49, 54, 48, 114, 66, 73, 122, 121, 109, 79, 54, 43, 79, 43, 55, 86, 111, 98, 119, 72, 68, 53, 90, 107, 115, 100, 86, 119, 51, 76, 68, 77, 74, 109, 75, 116, 89, 88, 83, 56, 77, 49, 88, 52, 56, 115, 86, 69, 115, 65, 69, 66, 81, 121, 90, 88, 48, 55, 55, 116, 51, 53, 110, 79, 65, 66, 121, 90, 75, 117, 112, 90, 120, 52, 97, 81, 61, 61]], Node[description=ref, content=[50, 64, 48, 100, 85, 56, 87, 87, 97, 119, 79, 65, 97, 47, 114, 97, 116, 122, 66, 101, 116, 111, 49, 98, 51, 56, 75, 43, 120, 72, 67, 81, 53, 105, 57, 84, 72, 120, 122, 79, 107, 82, 50, 121, 111, 108, 109, 104, 105, 119, 106, 51, 48, 70, 112, 101, 115, 90, 78, 47, 108, 47, 115, 56, 104, 116, 69, 71, 66, 106, 117, 68, 84, 47, 97, 83, 88, 80, 54, 103, 61, 61]], Node[description=ref, content=[50, 64, 99, 114, 65, 104, 117, 82, 88, 117, 71, 43, 73, 75, 56, 97, 49, 97, 54, 115, 100, 81, 88, 68, 53, 65, 89, 81, 98, 115, 54, 50, 97, 98, 118, 73, 79, 51, 75, 106, 69, 113, 54, 57, 121, 120, 56, 85, 56, 98, 82, 105, 52, 68, 118, 83, 78, 72, 73, 115, 112, 85, 118, 51, 75, 75, 100, 116, 106, 81, 66, 67, 52, 53, 76, 88, 56, 121, 77, 65, 61, 61]], Node[description=ref, content=[50, 64, 106, 52, 72, 122, 54, 121, 72, 120, 122, 85, 69, 53, 90, 82, 53, 117, 89, 71, 101, 112, 85, 100, 119, 103, 81, 85, 114, 49, 121, 76, 47, 82, 102, 57, 74, 112, 88, 75, 90, 51, 52, 54, 70, 77, 65, 106, 109, 76, 118, 114, 105, 69, 79, 76, 88, 71, 118, 115, 57, 114, 49, 50, 82, 57, 81, 50, 102, 86, 53, 90, 104, 99, 105, 84, 80, 85, 49, 65, 61, 61]]]]]]`

Something like

```
<iq from="s.whatsapp.net" id="1318268663" type="set" xmlns="md">
  <pair-device>
    <ref>2@vOGk/qqQUSJhABwyRq37vcCFF67Mi64JqKEKw44P2OYQV2QCzGOXQyOESdEa/YIzdpEiQaVNtiKimg==</ref>
    <ref>2@+To9XRMMANHz8MET3ND8xiPThhgAncDp9ncH6H3Q85+JM8pvg2lP4MIDWZCgo14IWhtt4j7Uo3gtYA==</ref>
    <ref>2@3RtAXSj0BTzUfrau3WSW8UjG+VgdzNATi1yVSeIJkpBELtT7e2YB7gFz0+ZH9SYkirhMmbkk1SHTnQ==</ref>
    <ref>2@IKsEuPrBi2yjWwvs44mFapglLQvIe6yg7/aVA6Vr+XiWAGwp7QV7204LpMDuhmhoqmVApHvW1IrP5g==</ref>
    <ref>2@ZHo7locQZNpaoOIAB7oVH+CWxgt9WuJ+Tzq/OiNpYYMqXkYgf1Kv5t16eGD+Rr2ZGyjnkxnzESXXaw==</ref>
    <ref>2@24slCL2j4D7E4cflcW1KWPPpaExBFSXV1SSrMyRtI4ZbMyUKE1OfphuaiDQ1mQJv9jD6g7ItRlQRSg==</ref>
  </pair-device>
</iq>
```

And also print data, non ASCII byte arrays like this 
`content=[Node[description=key, content=[1, 1, 0, -68, -33, -5, 78, 81, -38, 28, 83, 53, -18, -31, -101, -110, 38, 85, -18, -106, 111, -46, -16, -127, -101, -1, 114, 35, 78, 51, 60, -5, 22, 27, -65]]]]`
in hex format instead of decimals

**Comment by Auties00** [comment]
> @Auties00 , is it possible to print the analyzer data in XLMNS format instead of this decoded structure?
> 
> For example, this "pair-device" message
> 
> Instead of printing
> 
> `Received Binary Message Node[description=iq, attributes={xmlns=md, from=s.whatsapp.net, id=1155676853, type=set}, content=[Node[description=pair-device, content=[Node[description=ref, content=[50, 64, 86, 53, 75, 109, 106, 76, 119, 85, 87, 87, 81, 97, 112, 67, 105, 72, 78, 106, 55, 89, 66, 119, 83, 53, 72, 50, 100, 80, 100, 122, 101, 116, 67, 121, 85, 112, 101, 111, 49, 104, 106, 72, 104, 65, 122, 102, 53, 97, 68, 51, 85, 112, 120, 80, 99, 57, 53, 57, 48, 104, 71, 75, 65, 76, 66, 77, 119, 57, 55, 120, 85, 67, 103, 84, 81, 105, 74, 119, 61, 61]], Node[description=ref, content=[50, 64, 71, 87, 114, 75, 66, 49, 113, 48, 67, 112, 99, 111, 115, 72, 43, 52, 75, 111, 65, 86, 111, 69, 66, 98, 84, 74, 98, 48, 122, 70, 114, 74, 68, 120, 103, 54, 112, 75, 70, 67, 85, 69, 73, 55, 80, 83, 71, 65, 88, 83, 51, 120, 50, 121, 73, 97, 71, 69, 47, 105, 76, 73, 73, 51, 90, 103, 110, 89, 115, 115, 73, 104, 87, 75, 75, 107, 52, 103, 61, 61]], Node[description=ref, content=[50, 64, 82, 99, 49, 54, 48, 114, 66, 73, 122, 121, 109, 79, 54, 43, 79, 43, 55, 86, 111, 98, 119, 72, 68, 53, 90, 107, 115, 100, 86, 119, 51, 76, 68, 77, 74, 109, 75, 116, 89, 88, 83, 56, 77, 49, 88, 52, 56, 115, 86, 69, 115, 65, 69, 66, 81, 121, 90, 88, 48, 55, 55, 116, 51, 53, 110, 79, 65, 66, 121, 90, 75, 117, 112, 90, 120, 52, 97, 81, 61, 61]], Node[description=ref, content=[50, 64, 48, 100, 85, 56, 87, 87, 97, 119, 79, 65, 97, 47, 114, 97, 116, 122, 66, 101, 116, 111, 49, 98, 51, 56, 75, 43, 120, 72, 67, 81, 53, 105, 57, 84, 72, 120, 122, 79, 107, 82, 50, 121, 111, 108, 109, 104, 105, 119, 106, 51, 48, 70, 112, 101, 115, 90, 78, 47, 108, 47, 115, 56, 104, 116, 69, 71, 66, 106, 117, 68, 84, 47, 97, 83, 88, 80, 54, 103, 61, 61]], Node[description=ref, content=[50, 64, 99, 114, 65, 104, 117, 82, 88, 117, 71, 43, 73, 75, 56, 97, 49, 97, 54, 115, 100, 81, 88, 68, 53, 65, 89, 81, 98, 115, 54, 50, 97, 98, 118, 73, 79, 51, 75, 106, 69, 113, 54, 57, 121, 120, 56, 85, 56, 98, 82, 105, 52, 68, 118, 83, 78, 72, 73, 115, 112, 85, 118, 51, 75, 75, 100, 116, 106, 81, 66, 67, 52, 53, 76, 88, 56, 121, 77, 65, 61, 61]], Node[description=ref, content=[50, 64, 106, 52, 72, 122, 54, 121, 72, 120, 122, 85, 69, 53, 90, 82, 53, 117, 89, 71, 101, 112, 85, 100, 119, 103, 81, 85, 114, 49, 121, 76, 47, 82, 102, 57, 74, 112, 88, 75, 90, 51, 52, 54, 70, 77, 65, 106, 109, 76, 118, 114, 105, 69, 79, 76, 88, 71, 118, 115, 57, 114, 49, 50, 82, 57, 81, 50, 102, 86, 53, 90, 104, 99, 105, 84, 80, 85, 49, 65, 61, 61]]]]]]`
> 
> Something like
> 
> ```
> <iq from="s.whatsapp.net" id="1318268663" type="set" xmlns="md">
>   <pair-device>
>     <ref>2@vOGk/qqQUSJhABwyRq37vcCFF67Mi64JqKEKw44P2OYQV2QCzGOXQyOESdEa/YIzdpEiQaVNtiKimg==</ref>
>     <ref>2@+To9XRMMANHz8MET3ND8xiPThhgAncDp9ncH6H3Q85+JM8pvg2lP4MIDWZCgo14IWhtt4j7Uo3gtYA==</ref>
>     <ref>2@3RtAXSj0BTzUfrau3WSW8UjG+VgdzNATi1yVSeIJkpBELtT7e2YB7gFz0+ZH9SYkirhMmbkk1SHTnQ==</ref>
>     <ref>2@IKsEuPrBi2yjWwvs44mFapglLQvIe6yg7/aVA6Vr+XiWAGwp7QV7204LpMDuhmhoqmVApHvW1IrP5g==</ref>
>     <ref>2@ZHo7locQZNpaoOIAB7oVH+CWxgt9WuJ+Tzq/OiNpYYMqXkYgf1Kv5t16eGD+Rr2ZGyjnkxnzESXXaw==</ref>
>     <ref>2@24slCL2j4D7E4cflcW1KWPPpaExBFSXV1SSrMyRtI4ZbMyUKE1OfphuaiDQ1mQJv9jD6g7ItRlQRSg==</ref>
>   </pair-device>
> </iq>
> ```
> 
> And also print data, non ASCII byte arrays like this `content=[Node[description=key, content=[1, 1, 0, -68, -33, -5, 78, 81, -38, 28, 83, 53, -18, -31, -101, -110, 38, 85, -18, -106, 111, -46, -16, -127, -101, -1, 114, 35, 78, 51, 60, -5, 22, 27, -65]]]]` in hex format instead of decimals

Yes, modify the node#toString method
