### ISSUE TITLE
this tool works great

### ISSUE THREAD

**Issue by sugarjohnny** [Auties00/WhatsappWebRequestAnalyzer#2]
i can see all information sent through whatsapp.

is there a way to edit this using the tool though or no?

**Comment by Auties00** [comment]
> i can see all information sent through whatsapp.
> 
> is there a way to edit this using the tool though or no?

Thanks, it took a lot of work xF
Currently, I haven't implemented a system to send custom requests or modify them, but I developed an API called WhatsappWeb4j that may provide what you need

**Comment by sugarjohnny** [comment]
Yea your API is great but sadly it will lead to lots more scam bots flooding WhatsApp 

Still very cool and has lots of potential to create fun stuff on whatsapp
