### ISSUE TITLE
find public % private keys

### ISSUE THREAD

**Issue by barmoudeh** [Auties00/WhatsappWebRequestAnalyzer#3]
Hi
so tnx for your great project, how can I find the keys by this project?

**Comment by Auties00** [comment]
> so tnx for your great project, how can I find the keys by this project?

it does everything automatically, the keys are automatically extracted using Chrome dev tools. You only have to scan the QR code

**Comment by barmoudeh** [comment]
I know thanks, but can you tell me how can I extract public and private keys by chrome dev tool?

**Comment by Auties00** [comment]
> I know thanks, but can you tell me how can I extract public and private keys by chrome dev tool?

Do you want to print them from my tool or do you want an explanation on how I extract them?

**Comment by barmoudeh** [comment]
an explanation plz

**Comment by Auties00** [comment]
> an explanation plz

Okay, so this is how you do it:
1. Open an incognito page or a page where you haven't logged into WhatsApp web yet.
2. Open Chrome dev tools(F12)
3. Go to the sources tab
4. Look for a js script whose name contains bootstrap_qr(ex bootstrap_qr.21cdeb5afaacd0e5706a.js)
5. Beautify the file as it's kind of impossible to understand anything(there is an icon at the bottom left)
6. Search for this string: keyPair: t,
7. Put a breakpoint there
8. Reload the page and wait for the breakpoint to trigger
9. The data you are looking for is under Scope -> Local > a -> t

**Comment by barmoudeh** [comment]
> > an explanation plz
> 
> 
> 
> Okay, so this is how you do it:
> 
> 1. Open an incognito page or a page where you haven't logged into WhatsApp web yet.
> 
> 2. Open Chrome dev tools(F12)
> 
> 3. Go to the sources tab
> 
> 4. Look for a js script whose name contains bootstrap_qr(ex bootstrap_qr.21cdeb5afaacd0e5706a.js)
> 
> 5. Beautify the file as it's kind of impossible to understand anything(there is an icon at the bottom left)
> 
> 6. Search for this string: keyPair: t,
> 
> 7. Put a breakpoint there
> 
> 8. Reload the page and wait for the breakpoint to trigger
> 
> 9. The data you are looking for is under Scope -> Local > a -> t
> 
> 
> 
> 
> 
> 
> 
> 

thanks for your complete answer but in level 8 it just loading and dont show that data in scope part.

**Comment by barmoudeh** [comment]
finally I find it tnx for your help
