### ISSUE TITLE
Could not find com.github.auties00:standard:2.2.2-SNAPSHOT.

### ISSUE THREAD

**Issue by FreedomLabsIO** [Auties00/WhatsappWebRequestAnalyzer#5]
Hi @Auties00 , I'm trying to recompile the project because the provided release do not work with latest version of Chrome 96.
But I get this error when building it.

![image](https://user-images.githubusercontent.com/5354345/142676447-6369ce3a-1dab-4811-8e83-6f92de6b85dd.png)

So I tried adding the JitPack repository because of the GitHub dependencies

```
repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://jitpack.io")
    }
}
```

But now a "Could not resolve..." error appears

![image](https://user-images.githubusercontent.com/5354345/142677614-42673899-39f9-4f96-856a-710def321dd4.png)

**Comment by Auties00** [comment]
> Hi @Auties00 , I'm trying to recompile the project because the provided release do not work with latest version of Chrome 96. But I get this error when building it.
> 
> ![image](https://user-images.githubusercontent.com/5354345/142676447-6369ce3a-1dab-4811-8e83-6f92de6b85dd.png)
> 
> So I tried adding the JitPack repository because of the GitHub dependencies
> 
> ```
> repositories {
>     mavenCentral()
>     mavenLocal()
>     maven {
>         url = uri("https://jitpack.io")
>     }
> }
> ```
> 
> But now a "Could not resolve..." error appears
> 
> ![image](https://user-images.githubusercontent.com/5354345/142677614-42673899-39f9-4f96-856a-710def321dd4.png)

replace 2.2.2-SNAPSHOT with 2.2.2 and remove the jitpack import

**Comment by FreedomLabsIO** [comment]
> replace 2.2.2-SNAPSHOT with 2.2.2 and remove the jitpack import

Ok, now a similar error appears

![image](https://user-images.githubusercontent.com/5354345/142678809-e012e854-ac1f-4ba1-beaf-039a54ac039c.png)



https://repo.maven.apache.org/maven2/com/github/auties00/standard/2.2.2/standard-2.2.2.pom
```
404 Not Found
nginx
```

There are no "standard" and "multidevice" repositories in Maven

https://repo.maven.apache.org/maven2/com/github/auties00/

```
com/github/auties00
../
delombok-plugin/                                                 -         -      
noise-java/                                                      -         -      
optional/                                                        -         -      
protoc/                                                          -         -      
protoc-api/                                                      -         -      
protoc-parser/                                                   -         -      
protoc-tool/                                                     -         -      
reified/                                                         -         -      
whatsappweb4j/                                                   -         -      
maven-metadata.xml                                2021-05-05 13:24       253      
maven-metadata.xml.md5                            2021-05-05 13:24        32      
maven-metadata.xml.sha1                           2021-05-05 13:24        40      
maven-metadata.xml.sha256                         2021-05-05 13:24        64      
maven-metadata.xml.sha512                         2021-05-05 13:24       128      
```

**Comment by Auties00** [comment]
> 

Oh yeah use whatsappweb4j

**Comment by FreedomLabsIO** [comment]
> > 
> 
> Oh yeah use whatsappweb4j

Ok

```
dependencies {
    implementation("com.github.auties00", "whatsappweb4j", "2.2.2")
//    implementation("com.github.auties00", "multidevice", "2.2.2")
    implementation("org.seleniumhq.selenium", "selenium-java", "4.0.0-beta-3")
    implementation("org.seleniumhq.selenium", "selenium-devtools-v90", "4.0.0-beta-3")
    implementation("org.bouncycastle", "bcpkix-jdk15on", "1.68")
}
```

But what about multidevice?

![image](https://user-images.githubusercontent.com/5354345/142736960-866520ca-ff93-49e3-98b5-70100780a528.png)

**Comment by Auties00** [comment]
> > > 
> > 
> > 
> > Oh yeah use whatsappweb4j
> 
> Ok
> 
> ```
> dependencies {
>     implementation("com.github.auties00", "whatsappweb4j", "2.2.2")
> //    implementation("com.github.auties00", "multidevice", "2.2.2")
>     implementation("org.seleniumhq.selenium", "selenium-java", "4.0.0-beta-3")
>     implementation("org.seleniumhq.selenium", "selenium-devtools-v90", "4.0.0-beta-3")
>     implementation("org.bouncycastle", "bcpkix-jdk15on", "1.68")
> }
> ```
> 
> But what about multidevice?
> 
> ![image](https://user-images.githubusercontent.com/5354345/142736960-866520ca-ff93-49e3-98b5-70100780a528.png)

Yeah, I just remembered the problem. You will not be able to compile the project locally because the version of whatsappweb4j that you need isn't released yet. Clean everything that you've done and do something like:
```
git clone https://github.com/Auties00/WhatsappWeb4j.git
cd ./WhatsappWeb4j
git checkout multidevice
mvn install
```
And then try to build the analyzer, remember to add mavenLocal as a repository in gradle

**Comment by brunoaduarte** [comment]
> 
> Yeah, I just remembered the problem. You will not be able to compile the project locally because the version of whatsappweb4j that you need isn't released yet. Clean everything that you've done and do something like:
> 
> ```
> git clone https://github.com/Auties00/WhatsappWeb4j.git
> cd ./WhatsappWeb4j
> git checkout multidevice
> mvn install
> ```
> 
> And then try to build the analyzer, remember to add mavenLocal as a repository in gradle

Error when building for "mvn install"
```
Cannot resolve com.github.auties00:common:2.2.2-SNAPSHOT
```
This library is missing

**Comment by brunoaduarte** [comment]
> 
> Yeah, I just remembered the problem. You will not be able to compile the project locally because the version of whatsappweb4j that you need isn't released yet. Clean everything that you've done and do something like:
> 
> ```
> git clone https://github.com/Auties00/WhatsappWeb4j.git
> cd ./WhatsappWeb4j
> git checkout multidevice
> mvn install
> ```
> 
> And then try to build the analyzer, remember to add mavenLocal as a repository in gradle

```
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 4 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 4 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] com.github.auties00:whatsappweb4j                                  [pom]
[INFO] common                                                             [jar]
[INFO] standard                                                           [jar]
[INFO] multidevice                                                        [jar]
[INFO]
[INFO] -----------------< com.github.auties00:whatsappweb4j >------------------
[INFO] Building com.github.auties00:whatsappweb4j 2.2.2-SNAPSHOT          [1/4]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- delombok-plugin:1.18.20:delombok (default) @ whatsappweb4j ---
[INFO] Starting delombok process...
[INFO] Detected 0 files
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for com.github.auties00:whatsappweb4j 2.2.2-SNAPSHOT:
[INFO]
[INFO] com.github.auties00:whatsappweb4j .................. FAILURE [  4.900 s]
[INFO] common ............................................. SKIPPED
[INFO] standard ........................................... SKIPPED
[INFO] multidevice ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.509 s
[INFO] Finished at: 2021-11-22T03:16:20-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.auties00:delombok-plugin:1.18.20:delombok (default) on project whatsappweb4j: Execution default of goal com.github.auties00:delombok-plugin:1.18.20:delombok failed: No value present -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by FreedomLabsIO** [comment]
> 
> Yeah, I just remembered the problem. You will not be able to compile the project locally because the version of whatsappweb4j that you need isn't released yet. Clean everything that you've done and do something like:
> 
> ```
> git clone https://github.com/Auties00/WhatsappWeb4j.git
> cd ./WhatsappWeb4j
> git checkout multidevice
> mvn install
> ```
> 
> And then try to build the analyzer, remember to add mavenLocal as a repository in gradle

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 4 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 4 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] com.github.auties00:whatsappweb4j                                  [pom]
[INFO] common                                                             [jar]
[INFO] standard                                                           [jar]
[INFO] multidevice                                                        [jar]
[INFO]
[INFO] -----------------< com.github.auties00:whatsappweb4j >------------------
[INFO] Building com.github.auties00:whatsappweb4j 2.2.2-SNAPSHOT          [1/4]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- delombok-plugin:1.18.20:delombok (default) @ whatsappweb4j ---
[INFO] Starting delombok process...
[INFO] Detected 0 files
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for com.github.auties00:whatsappweb4j 2.2.2-SNAPSHOT:
[INFO]
[INFO] com.github.auties00:whatsappweb4j .................. FAILURE [  4.239 s]
[INFO] common ............................................. SKIPPED
[INFO] standard ........................................... SKIPPED
[INFO] multidevice ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.863 s
[INFO] Finished at: 2021-11-22T03:42:06-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.auties00:delombok-plugin:1.18.20:delombok (default) on project whatsappweb4j: Execution default of goal com.github.auties00:delombok-plugin:1.18.20:delombok failed: No value present -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.auties00:delombok-plugin:1.18.20:delombok (default) on project whatsappweb4j: Execution default of goal com.github.auties00:delombok-plugin:1.18.20:delombok failed: No value present
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.auties00:delombok-plugin:1.18.20:delombok failed: No value present
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.util.NoSuchElementException: No value present
    at java.util.Optional.orElseThrow (Optional.java:377)
    at it.auties.delombok.DelombokMojo.findMatchingSourceFile (DelombokMojo.java:61)
    at it.auties.delombok.DelombokMojo.lambda$moveOutputToCorrectDir$1 (DelombokMojo.java:50)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:179)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:197)
    at java.util.Iterator.forEachRemaining (Iterator.java:133)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining (Spliterators.java:1845)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:596)
    at it.auties.delombok.DelombokMojo.moveOutputToCorrectDir (DelombokMojo.java:48)
    at it.auties.delombok.DelombokMojo.execute (DelombokMojo.java:40)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by Auties00** [comment]
> > Yeah, I just remembered the problem. You will not be able to compile the project locally because the version of whatsappweb4j that you need isn't released yet. Clean everything that you've done and do something like:
> > ```
> > git clone https://github.com/Auties00/WhatsappWeb4j.git
> > cd ./WhatsappWeb4j
> > git checkout multidevice
> > mvn install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then try to build the analyzer, remember to add mavenLocal as a repository in gradle
> 
> ```
> [INFO] Error stacktraces are turned on.
> [INFO] Scanning for projects...
> [INFO] Inspecting build with total of 4 modules...
> [INFO] Installing Nexus Staging features:
> [INFO]   ... total of 4 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Build Order:
> [INFO]
> [INFO] com.github.auties00:whatsappweb4j                                  [pom]
> [INFO] common                                                             [jar]
> [INFO] standard                                                           [jar]
> [INFO] multidevice                                                        [jar]
> [INFO]
> [INFO] -----------------< com.github.auties00:whatsappweb4j >------------------
> [INFO] Building com.github.auties00:whatsappweb4j 2.2.2-SNAPSHOT          [1/4]
> [INFO] --------------------------------[ pom ]---------------------------------
> [INFO]
> [INFO] --- delombok-plugin:1.18.20:delombok (default) @ whatsappweb4j ---
> [INFO] Starting delombok process...
> [INFO] Detected 0 files
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for com.github.auties00:whatsappweb4j 2.2.2-SNAPSHOT:
> [INFO]
> [INFO] com.github.auties00:whatsappweb4j .................. FAILURE [  4.239 s]
> [INFO] common ............................................. SKIPPED
> [INFO] standard ........................................... SKIPPED
> [INFO] multidevice ........................................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  4.863 s
> [INFO] Finished at: 2021-11-22T03:42:06-03:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.github.auties00:delombok-plugin:1.18.20:delombok (default) on project whatsappweb4j: Execution default of goal com.github.auties00:delombok-plugin:1.18.20:delombok failed: No value present -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.auties00:delombok-plugin:1.18.20:delombok (default) on project whatsappweb4j: Execution default of goal com.github.auties00:delombok-plugin:1.18.20:delombok failed: No value present
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:568)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.auties00:delombok-plugin:1.18.20:delombok failed: No value present
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:568)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> Caused by: java.util.NoSuchElementException: No value present
>     at java.util.Optional.orElseThrow (Optional.java:377)
>     at it.auties.delombok.DelombokMojo.findMatchingSourceFile (DelombokMojo.java:61)
>     at it.auties.delombok.DelombokMojo.lambda$moveOutputToCorrectDir$1 (DelombokMojo.java:50)
>     at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
>     at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:179)
>     at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:197)
>     at java.util.Iterator.forEachRemaining (Iterator.java:133)
>     at java.util.Spliterators$IteratorSpliterator.forEachRemaining (Spliterators.java:1845)
>     at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
>     at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
>     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
>     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
>     at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
>     at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:596)
>     at it.auties.delombok.DelombokMojo.moveOutputToCorrectDir (DelombokMojo.java:48)
>     at it.auties.delombok.DelombokMojo.execute (DelombokMojo.java:40)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:568)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> [ERROR]
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
> ```

Try with mvn clean install

**Comment by brunoaduarte** [comment]
> 
> Try with mvn clean install

I was already running "clean" before "install"... same issue...

Are you using these same version of this tools?

```
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.4
Java version: 17.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
