### ISSUE TITLE
Could not start a new session

### ISSUE THREAD

**Issue by Ased2235** [Auties00/WhatsappWebRequestAnalyzer#8]
Hello, i'm getting this error when i tried to run it.
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
/home/senpai/chromedriver.exe: 3: Syntax error: Unterminated quoted string
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:99)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:86)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:41)
	at it.auties.whatsapp4j.MainKt.initializeSelenium(main.kt:124)
	at it.auties.whatsapp4j.MainKt.main(main.kt:34)
Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
System info: host: 'senpai-pc', ip: '192.xxx.xxx.x', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-41-generic', java.version: '16'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:220)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:86)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:619)
	... 8 more

```

**Comment by Auties00** [comment]
> Hello, i'm getting this error when i tried to run it.
> 
> ```
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> /home/senpai/chromedriver.exe: 3: Syntax error: Unterminated quoted string
> Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
> 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
> 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)
> 	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:89)
> 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:99)
> 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:86)
> 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:41)
> 	at it.auties.whatsapp4j.MainKt.initializeSelenium(main.kt:124)
> 	at it.auties.whatsapp4j.MainKt.main(main.kt:34)
> Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
> Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
> System info: host: 'senpai-pc', ip: '192.xxx.xxx.x', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-41-generic', java.version: '16'
> Driver info: driver.version: ChromeDriver
> 	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:220)
> 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:86)
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:619)
> 	... 8 more
> ```

Can you check out the latest release?

**Comment by Ased2235** [comment]
> > Hello, i'm getting this error when i tried to run it.
> > ```
> > SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> > SLF4J: Defaulting to no-operation (NOP) logger implementation
> > SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> > /home/senpai/chromedriver.exe: 3: Syntax error: Unterminated quoted string
> > Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
> > 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
> > 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)
> > 	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:89)
> > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:99)
> > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:86)
> > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:41)
> > 	at it.auties.whatsapp4j.MainKt.initializeSelenium(main.kt:124)
> > 	at it.auties.whatsapp4j.MainKt.main(main.kt:34)
> > Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
> > Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
> > System info: host: 'senpai-pc', ip: '192.xxx.xxx.x', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-41-generic', java.version: '16'
> > Driver info: driver.version: ChromeDriver
> > 	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:220)
> > 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:86)
> > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:619)
> > 	... 8 more
> > ```
> 
> Can you check out the latest release?

Thanks it worked!!
But is there anyway to docode `content=[B@d763dc]`, For example this

` Sent Binary Message Node[description=iq, attributes={xmlns=w:sync:app:state, to=s.whatsapp.net, id=5280.30154-86, type=set}, content=[Node[description=sync, attributes={}, content=[Node[description=collection, attributes={name=regular_high, return_snapshot=false, version=49}, content=[Node[description=patch, attributes={}, content=[B@d763dc]]]]]]]
`

**Comment by Auties00** [comment]
> > > Hello, i'm getting this error when i tried to run it.
> > > ```
> > > SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> > > SLF4J: Defaulting to no-operation (NOP) logger implementation
> > > SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> > > /home/senpai/chromedriver.exe: 3: Syntax error: Unterminated quoted string
> > > Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> > > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
> > > 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
> > > 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)
> > > 	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:89)
> > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:99)
> > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:86)
> > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:41)
> > > 	at it.auties.whatsapp4j.MainKt.initializeSelenium(main.kt:124)
> > > 	at it.auties.whatsapp4j.MainKt.main(main.kt:34)
> > > Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
> > > Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
> > > System info: host: 'senpai-pc', ip: '192.xxx.xxx.x', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-41-generic', java.version: '16'
> > > Driver info: driver.version: ChromeDriver
> > > 	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:220)
> > > 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:86)
> > > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:619)
> > > 	... 8 more
> > > ```
> > 
> > 
> > Can you check out the latest release?
> 
> Thanks it worked!! But is there anyway to docode `content=[B@d763dc]`, For example this
> 
> `Sent Binary Message Node[description=iq, attributes={xmlns=w:sync:app:state, to=s.whatsapp.net, id=5280.30154-86, type=set}, content=[Node[description=sync, attributes={}, content=[Node[description=collection, attributes={name=regular_high, return_snapshot=false, version=49}, content=[Node[description=patch, attributes={}, content=[B@d763dc]]]]]]]`

Yeah it's just an array of bytes. Do you need the content?

**Comment by Ased2235** [comment]
> > > > Hello, i'm getting this error when i tried to run it.
> > > > ```
> > > > SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> > > > SLF4J: Defaulting to no-operation (NOP) logger implementation
> > > > SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> > > > /home/senpai/chromedriver.exe: 3: Syntax error: Unterminated quoted string
> > > > Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> > > > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
> > > > 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
> > > > 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)
> > > > 	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:89)
> > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:99)
> > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:86)
> > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:41)
> > > > 	at it.auties.whatsapp4j.MainKt.initializeSelenium(main.kt:124)
> > > > 	at it.auties.whatsapp4j.MainKt.main(main.kt:34)
> > > > Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
> > > > Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
> > > > System info: host: 'senpai-pc', ip: '192.xxx.xxx.x', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-41-generic', java.version: '16'
> > > > Driver info: driver.version: ChromeDriver
> > > > 	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:220)
> > > > 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:86)
> > > > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:619)
> > > > 	... 8 more
> > > > ```
> > > 
> > > 
> > > Can you check out the latest release?
> > 
> > 
> > Thanks it worked!! But is there anyway to docode `content=[B@d763dc]`, For example this
> > `Sent Binary Message Node[description=iq, attributes={xmlns=w:sync:app:state, to=s.whatsapp.net, id=5280.30154-86, type=set}, content=[Node[description=sync, attributes={}, content=[Node[description=collection, attributes={name=regular_high, return_snapshot=false, version=49}, content=[Node[description=patch, attributes={}, content=[B@d763dc]]]]]]]`
> 
> Yeah it's just an array of bytes. Do you need the content?

Yes if possible,  I'm been looking into this for few weeks but still no luck. I tried JS too but still nothing.

**Comment by Auties00** [comment]
> > > > > Hello, i'm getting this error when i tried to run it.
> > > > > ```
> > > > > SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> > > > > SLF4J: Defaulting to no-operation (NOP) logger implementation
> > > > > SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> > > > > /home/senpai/chromedriver.exe: 3: Syntax error: Unterminated quoted string
> > > > > Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
> > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
> > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)
> > > > > 	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:89)
> > > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:99)
> > > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:86)
> > > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:41)
> > > > > 	at it.auties.whatsapp4j.MainKt.initializeSelenium(main.kt:124)
> > > > > 	at it.auties.whatsapp4j.MainKt.main(main.kt:34)
> > > > > Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
> > > > > Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
> > > > > System info: host: 'senpai-pc', ip: '192.xxx.xxx.x', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-41-generic', java.version: '16'
> > > > > Driver info: driver.version: ChromeDriver
> > > > > 	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:220)
> > > > > 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:86)
> > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:619)
> > > > > 	... 8 more
> > > > > ```
> > > > 
> > > > 
> > > > Can you check out the latest release?
> > > 
> > > 
> > > Thanks it worked!! But is there anyway to docode `content=[B@d763dc]`, For example this
> > > `Sent Binary Message Node[description=iq, attributes={xmlns=w:sync:app:state, to=s.whatsapp.net, id=5280.30154-86, type=set}, content=[Node[description=sync, attributes={}, content=[Node[description=collection, attributes={name=regular_high, return_snapshot=false, version=49}, content=[Node[description=patch, attributes={}, content=[B@d763dc]]]]]]]`
> > 
> > 
> > Yeah it's just an array of bytes. Do you need the content?
> 
> Yes if possible, I'm been looking into this for few weeks but still no luck. I tried JS too but still nothing.

Uhm you could edit the source and add a check if Node#content is an array of bytes than print the hex/array instead of the address

**Comment by Ased2235** [comment]
> > > > > > Hello, i'm getting this error when i tried to run it.
> > > > > > ```
> > > > > > SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> > > > > > SLF4J: Defaulting to no-operation (NOP) logger implementation
> > > > > > SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> > > > > > /home/senpai/chromedriver.exe: 3: Syntax error: Unterminated quoted string
> > > > > > Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> > > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
> > > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
> > > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)
> > > > > > 	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:89)
> > > > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:99)
> > > > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:86)
> > > > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:41)
> > > > > > 	at it.auties.whatsapp4j.MainKt.initializeSelenium(main.kt:124)
> > > > > > 	at it.auties.whatsapp4j.MainKt.main(main.kt:34)
> > > > > > Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
> > > > > > Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
> > > > > > System info: host: 'senpai-pc', ip: '192.xxx.xxx.x', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-41-generic', java.version: '16'
> > > > > > Driver info: driver.version: ChromeDriver
> > > > > > 	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:220)
> > > > > > 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:86)
> > > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:619)
> > > > > > 	... 8 more
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Can you check out the latest release?
> > > > 
> > > > 
> > > > Thanks it worked!! But is there anyway to docode `content=[B@d763dc]`, For example this
> > > > `Sent Binary Message Node[description=iq, attributes={xmlns=w:sync:app:state, to=s.whatsapp.net, id=5280.30154-86, type=set}, content=[Node[description=sync, attributes={}, content=[Node[description=collection, attributes={name=regular_high, return_snapshot=false, version=49}, content=[Node[description=patch, attributes={}, content=[B@d763dc]]]]]]]`
> > > 
> > > 
> > > Yeah it's just an array of bytes. Do you need the content?
> > 
> > 
> > Yes if possible, I'm been looking into this for few weeks but still no luck. I tried JS too but still nothing.
> 
> Uhm you could edit the source and add a check if Node#content is an array of bytes than print the hex/array instead of the address

Eh... I'm trying that but idk how, you see I'm not good at kt/Java.

**Comment by Auties00** [comment]
> > > > > > > Hello, i'm getting this error when i tried to run it.
> > > > > > > ```
> > > > > > > SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> > > > > > > SLF4J: Defaulting to no-operation (NOP) logger implementation
> > > > > > > SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> > > > > > > /home/senpai/chromedriver.exe: 3: Syntax error: Unterminated quoted string
> > > > > > > Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> > > > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
> > > > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
> > > > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)
> > > > > > > 	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:89)
> > > > > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:99)
> > > > > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:86)
> > > > > > > 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:41)
> > > > > > > 	at it.auties.whatsapp4j.MainKt.initializeSelenium(main.kt:124)
> > > > > > > 	at it.auties.whatsapp4j.MainKt.main(main.kt:34)
> > > > > > > Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
> > > > > > > Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
> > > > > > > System info: host: 'senpai-pc', ip: '192.xxx.xxx.x', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-41-generic', java.version: '16'
> > > > > > > Driver info: driver.version: ChromeDriver
> > > > > > > 	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:220)
> > > > > > > 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:86)
> > > > > > > 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:619)
> > > > > > > 	... 8 more
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Can you check out the latest release?
> > > > > 
> > > > > 
> > > > > Thanks it worked!! But is there anyway to docode `content=[B@d763dc]`, For example this
> > > > > `Sent Binary Message Node[description=iq, attributes={xmlns=w:sync:app:state, to=s.whatsapp.net, id=5280.30154-86, type=set}, content=[Node[description=sync, attributes={}, content=[Node[description=collection, attributes={name=regular_high, return_snapshot=false, version=49}, content=[Node[description=patch, attributes={}, content=[B@d763dc]]]]]]]`
> > > > 
> > > > 
> > > > Yeah it's just an array of bytes. Do you need the content?
> > > 
> > > 
> > > Yes if possible, I'm been looking into this for few weeks but still no luck. I tried JS too but still nothing.
> > 
> > 
> > Uhm you could edit the source and add a check if Node#content is an array of bytes than print the hex/array instead of the address
> 
> Eh... I'm trying that but idk how, you see I'm not good at kt/Java.

I'll do it for you tomorrow, just remind me with a tag if I don't release anything

**Comment by Ased2235** [comment]
@Auties00 Any update?

**Comment by Ased2235** [comment]
@Auties00 Hello, Any update?
