### ISSUE TITLE
Selenium upgrade to v4.1.0 for 96

### ISSUE THREAD

**Issue by 1337-sys** [Auties00/WhatsappWebRequestAnalyzer#9]
```
➜  WhatsappWebRequestAnalyzer ./run.bash 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 23870
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Dec 06, 2021 2:06:29 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Dec 06, 2021 2:06:29 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 96, so returning the closest version found: a no-op implementation
Dec 06, 2021 2:06:29 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Unable to find CDP implementation matching 96.
Dec 06, 2021 2:06:29 AM org.openqa.selenium.chromium.ChromiumDriver lambda$new$2
WARNING: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to org.seleniumhq.selenium:selenium-devtools-v86:4.0.0-beta-3 where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
Exception in thread "main" org.openqa.selenium.devtools.DevToolsException: You are using a no-op implementation of the CDP. The most likely reason for this is that Selenium was unable to find an implementation of the CDP protocol that matches your browser. Please be sure to include an implementation on the classpath, possibly by adding a new (maven) dependency of org.seleniumhq.selenium:selenium-devtools-vNN:4.0.0-beta-3 where NN matches the major version of the browser you're using.
Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
System info: host: 'Ubuntu1337', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-40-generic', java.version: '16'
Driver info: DevTools Connection
  at org.openqa.selenium.devtools.noop.NoOpDomains.target(NoOpDomains.java:59)
  at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:91)
  at it.auties.whatsapp4j.MainKt.main(main.kt:36)
```

Selenium is upgraded to current [v4.1.0 ](https://github.com/SeleniumHQ/selenium/blob/201fad38296f9ea47ac1b1b59c160963dc7b2907/java/CHANGELOG#L1)where: 

- Supported CDP versions: 85, 94, 95, 96

**Comment by Auties00** [comment]
> ```
> ➜  WhatsappWebRequestAnalyzer ./run.bash 
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 23870
> Only local connections are allowed.
> Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
> ChromeDriver was started successfully.
> Dec 06, 2021 2:06:29 AM org.openqa.selenium.remote.ProtocolHandshake createSession
> INFO: Detected dialect: W3C
> Dec 06, 2021 2:06:29 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
> WARNING: Unable to find an exact match for CDP version 96, so returning the closest version found: a no-op implementation
> Dec 06, 2021 2:06:29 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
> INFO: Unable to find CDP implementation matching 96.
> Dec 06, 2021 2:06:29 AM org.openqa.selenium.chromium.ChromiumDriver lambda$new$2
> WARNING: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to org.seleniumhq.selenium:selenium-devtools-v86:4.0.0-beta-3 where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
> Exception in thread "main" org.openqa.selenium.devtools.DevToolsException: You are using a no-op implementation of the CDP. The most likely reason for this is that Selenium was unable to find an implementation of the CDP protocol that matches your browser. Please be sure to include an implementation on the classpath, possibly by adding a new (maven) dependency of org.seleniumhq.selenium:selenium-devtools-vNN:4.0.0-beta-3 where NN matches the major version of the browser you're using.
> Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
> System info: host: 'Ubuntu1337', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-40-generic', java.version: '16'
> Driver info: DevTools Connection
>   at org.openqa.selenium.devtools.noop.NoOpDomains.target(NoOpDomains.java:59)
>   at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:91)
>   at it.auties.whatsapp4j.MainKt.main(main.kt:36)
> ```
> 
> Selenium is upgraded to current [v4.1.0 ](https://github.com/SeleniumHQ/selenium/blob/201fad38296f9ea47ac1b1b59c160963dc7b2907/java/CHANGELOG#L1)where:
> 
> * Supported CDP versions: 85, 94, 95, 96

did you try the latest release?
